plugins {
	id "com.crystaelix.loom" version "1.11.0"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "com.crystaelix.blossom" version "1.3.2"
	id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

repositories {
	mavenCentral()
	flatDir {
		dirs "libs"
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.crystaelix.com/releases/"
			}
		}
		filter {
			includeGroup "thelm.jaopca"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://nexus.gtnewhorizons.com/repository/public/"
				metadataSources {
					mavenPom()
					ignoreGradleMetadataRedirection()
				}
			}
		}
		filter {
			includeGroup "com.github.GTNewHorizons"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://jitpack.io/"
			}
		}
		filter {
			includeGroup "com.github.LegacyModdingMC.UniMixins"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com/"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
}

def mcVersion = "1.7.10"
def modName = "JAOPCASingularities"
def modId = "jaopcasingularities"
def specVersion = "W"
def vendor = "thelm"

group = "thelm.jaopca.singularities"
version = "W.0.1.5"

def archivesName = "${modName}-${mcVersion}"
base.archivesName = archivesName

sourceSets {
	main {
		output.resourcesDir = java.destinationDirectory = layout.buildDirectory.dir("outputs/main")
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
		vendor = JvmVendorSpec.AZUL
	}
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

loom {
	silentMojangMappingsLicense()
	runs {
		configureEach {
			property "fabric.log.console.level", "debug"
		}
		client {
			programArg "--username=Dev"
			vmArg "-Xmx7G"
		}
		server {
			vmArg "-Xmx3G"
		}
	}
	generatedIntermediateMappings()
}

dependencies {
	// Log4j
	implementation "org.apache.logging.log4j:log4j-core:2.24.3"

	// Minecraft
	minecraft "com.mojang:minecraft:1.7.10"
	mappings "net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10:userdev"
	legacyForge "net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10:universal"

	// Dependencies
	implementation("com.github.LegacyModdingMC.UniMixins:unimixins-all-1.7.10:0.1.22") {transitive = false}
	modImplementation "thelm.jaopca:JAOPCA-1.7.10:W.0.8.31"
	modImplementation "curse.maven:avaritia-233785:2519595"
	modImplementation "curse.maven:wanionlib-253043:2430662"
	modImplementation "curse.maven:eternal-singularity-253077:2577977"
	modImplementation("com.github.GTNewHorizons:CodeChickenLib:1.3.0") {transitive = false}
	modImplementation("com.github.GTNewHorizons:CodeChickenCore:1.4.3") {transitive = false}
	modImplementation("com.github.GTNewHorizons:NotEnoughItems:2.7.69-GTNH") {transitive = false}
	modImplementation "curse.maven:nei-integration-225251:2282522"

	// Testing
	modImplementation "curse.maven:hbms-nuclear-tech-mod-235439:6551129"

	// Performance
	modImplementation("com.github.GTNewHorizons:GTNHLib:0.6.31") {transitive = false}
	modImplementation("com.github.GTNewHorizons:NotEnoughIds:2.1.10") {transitive = false}
	modImplementation "curse.maven:archaicfix-677782:6785841"
}

def replacements = [
	"0@VERSION@": version
]

blossom {
	replaceToken(replacements)
}

processResources {
	inputs.properties(replacements)
	filesMatching(["mcmod.info", "META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
		filter {
			it.replace(replacements)
		}
	}
}

def manifestAttributes = [
	"Specification-Title": modName,
	"Specification-Vendor": vendor,
	"Specification-Version": specVersion,
	"Implementation-Title": archivesName,
	"Implementation-Version": version,
	"Implementation-Vendor": vendor
]

jar {
	manifest.attributes(manifestAttributes)
}

sourcesJar {
	manifest.attributes(manifestAttributes)
}

publishing {
	publications {
		register("mavenJava", MavenPublication) {
			artifactId = archivesName
			artifact remapJar
			artifact sourcesJar
		}
	}
	repositories {
		if(project.hasProperty("CrystaelixMavenUsername") && project.hasProperty("CrystaelixMavenPassword")) {
			maven {
				name = "CrystaelixMaven"
				url = "https://maven.crystaelix.com/releases/"
				credentials(PasswordCredentials)
			}
		}
	}
}

publishMods {
	file = remapJar.archiveFile
	version = displayName = "${mcVersion}-${project.version}"
	changelog = file("changelog.md").text
	type = ALPHA
	modLoaders.add("forge")
	additionalFiles.from(sourcesJar.archiveFile)

	curseforge {
		accessToken = providers.gradleProperty("curseforge.token")
		projectId = "268610"
		minecraftVersions.add(mcVersion)
		requires "jaopca", "avaritia"
		optional "eternal-singularity"
	}

	modrinth {
		accessToken = providers.gradleProperty("modrinth.token")
		projectId = "O9qb04PW"
		minecraftVersions.add(mcVersion)
		requires "jaopca"
	}
}
