package thelm.jaopca.singularities;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(
		modid = JAOPCASingularities.MOD_ID,
		name = JAOPCASingularities.NAME,
		version = JAOPCASingularities.VERSION,
		dependencies = JAOPCASingularities.DEPENDENCIES
		)
public class JAOPCASingularities {

	public static final String MOD_ID = "jaopcasingularities";
	public static final String NAME = "JAOPCASingularities";
	public static final String VERSION = "1.7.10-W.0.0.1";
	public static final String DEPENDENCIES = "required-after:Avaritia;required-before:jaopca@[1.7.10-W.0.1,);";
	@Instance(JAOPCASingularities.MOD_ID)
	public static JAOPCASingularities core;
	public static ModMetadata metadata;

	@EventHandler
	public void firstMovement(FMLPreInitializationEvent event) {
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.version = VERSION;
		metadata.credits = "Idea taken from AOBD Singularities by RCXCrafter";
		metadata.authorList.add("TheLMiffy1111");
		metadata.description = "A mod that aims to add singularities for more ores to Avaritia.";
	}
}
